version: "3"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

services:
  postgres:
    container_name: ztoec-postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  keycloak:
    container_name: ztoec-keycloak
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 2020
    volumes:
      - /keycloak/themes/genesis:/opt/jboss/keycloak/themes/genesis

    ports:
      - 8080:8080
    depends_on:
      - postgres

  redis:
    image: redis
    restart: always
    container_name: ztoec-redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
        