version: "3.6"

services:
  erc.households.indexing:
    container_name: "ztoec-indexing"
    image: ${DOCKER_REGISTRY}erc/households/indexing
    restart: always
    environment:
        RabbitMQ__ConnectionString: ${RabbitMQ__ConnectionString}
        RabbitMQ__UserName: ${RabbitMQ__UserName}
        RabbitMQ__Password: ${RabbitMQ__Password}
        ConnectionStrings__Elasticsearch: ${ConnectionStrings__Elasticsearch}

  erc.households.api:
    container_name: "ztoec-households-api"
    image: ${DOCKER_REGISTRY}erc/households/api
    restart: always
    environment:
        ConnectionStrings__ErcContext: ${ConnectionStrings__ErcContext}
        ConnectionStrings__Elasticsearch: ${ConnectionStrings__Elasticsearch}
        RabbitMQ__ConnectionString: ${RabbitMQ__ConnectionString}
        RabbitMQ__UserName: ${RabbitMQ__UserName}
        RabbitMQ__Password: ${RabbitMQ__Password}
    ports:
      - "5050:80"

  erc.households.ui:
    container_name: "ztoec-households-ui"
    image: ${DOCKER_REGISTRY}erc/households/ui
    restart: always
    ports:
      - "8888:80"

  erc.households.dso.bridge:
    container_name: "ztoec-households-dso-bridge"
    image: ${DOCKER_REGISTRY}erc/households/dso-bridge
    restart: always
    environment:
      RabbitMQ__ConnectionString: ${RabbitMQ__ConnectionString}
      RabbitMQ__UserName: ${RabbitMQ__UserName}
      RabbitMQ__Password: ${RabbitMQ__Password}
      ZtoeRabbitMQ__ConnectionString: ${ZtoeRabbitMQ__ConnectionString}
      ZtoeRabbitMQ__Username: ${ZtoeRabbitMQ__UserName}
      ZtoeRabbitMQ__Password: ${ZtoeRabbitMQ__Password}

networks:
  default:
    external:
      name: ztoec-erc