version: "3.6"

services:
  erc.households.indexing:
    container_name: "ztoec-indexing"
    image: ${DOCKER_REGISTRY}erc/households/indexing:latest
    restart: always

  erc.households.api:
    container_name: "ztoec-households-api"
    image: ${DOCKER_REGISTRY}erc/households/api:latest
    restart: always
    ports:
      - "5050:80"

  erc.households.printbills.api:
    container_name: "ztoec-households-printbills-api"
    image: ${DOCKER_REGISTRY}erc/households/printbills/api:latest
    restart: always
    ports:
      - "5060:80"

  erc.households.ui:
    container_name: "ztoec-households-ui"
    image: ${DOCKER_REGISTRY}erc/households/ui:latest
    restart: always
    ports:
      - "8888:80"
      
  erc.households.claculation:
    container_name: "ztoec-households-calculation"
    image: ${DOCKER_REGISTRY}erc/households/calculation:latest
    restart: always

  erc.households.dso.bridge:
    container_name: "ztoec-households-dso-bridge"
    image: ${DOCKER_REGISTRY}erc/households/dso-bridge:latest
    restart: always

networks:
  default:
    external:
      name: ztoec-erc