version: "3.6"

services:
  erc.households.indexing:
    container_name: "ztoec-indexing"
    image: ${DOCKER_REGISTRY}erc/households/indexing
    environment:
        RabbitMQ__ConnectionString: ${RabbitMQ__ConnectionString}
        RabbitMQ__UserName: ${RabbitMQ__UserName}
        RabbitMQ__Password: ${RabbitMQ__Password}
        ConnectionStrings__Elasticsearch: ${ConnectionStrings__Elasticsearch}

  erc.households.api:
    container_name: "ztoec-households-api"
    image: ${DOCKER_REGISTRY}erc/households/api
    environment:
        ConnectionStrings__ErcContext: ${ConnectionStrings__ErcContext}
        ConnectionStrings__Elasticsearch: ${ConnectionStrings__Elasticsearch}
    ports:
      - "5050:80"

  erc.households.ui:
    container_name: "ztoec-households-ui"
    image: ${DOCKER_REGISTRY}erc/households/ui
    ports:
      - "8888:80"

networks:
  default:
    external:
      name: ztoec-erc